name: CD - Deploy to Minikube using GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Build and Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t doc-assignment:latest .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy.yaml
          kubectl wait --for=condition=Ready pod -l app=doc-backend --timeout=90s
          kubectl get all
      - name: Test service URLs
        run: |
          echo "SERVICE_URL=$(minikube service doc-backend-service --url)"
          kubectl port-forward service/doc-backend-service 8081:8081 &> /dev/null &
          sleep 10
          curl -i
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete